/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package introductionbaseihm.secondefacon;

/**
 *
 * @author Max
 */
public class MonPanneau extends java.awt.Panel {

    private int compteur;

    /**
     * Creates new form MonPanneau
     */
    public MonPanneau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monLabel = new java.awt.Label();
        monBouton = new java.awt.Button();

        setLayout(new java.awt.GridLayout(2, 1));

        monLabel.setAlignment(java.awt.Label.CENTER);
        monLabel.setText("Tu n'as pas encore cliqué.");
        monLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monLabelMouseExited(evt);
            }
        });
        add(monLabel);
        monLabel.getAccessibleContext().setAccessibleName("");

        monBouton.setLabel("Cliquez.");
        monBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monBoutonMouseEntered(evt);
            }
        });
        monBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monBoutonActionPerformed(evt);
            }
        });
        add(monBouton);
        monBouton.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void monBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monBoutonActionPerformed
        compteur++;
        this.monLabel.setText("Tu as cliqué " + compteur + " fois.");
    }//GEN-LAST:event_monBoutonActionPerformed

    private void monLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monLabelMouseEntered
        System.out.println("La souris est entrée sur le label");
    }//GEN-LAST:event_monLabelMouseEntered

    private void monLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monLabelMouseExited
        System.out.println("La souris est sortie du label");
    }//GEN-LAST:event_monLabelMouseExited

    private void monBoutonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monBoutonMouseEntered
        System.out.println("La souris est entrée sur le bouton");
    }//GEN-LAST:event_monBoutonMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button monBouton;
    private java.awt.Label monLabel;
    // End of variables declaration//GEN-END:variables
}
